import React, { useState } from 'react';
import { PenLine } from 'lucide-react';
import MessageList from './MessageList';

const BlogCreationView = ({ messages, onSendMessage, isLoading }) => {
  const [userInput, setUserInput] = useState('');
  const [topicIdeas, setTopicIdeas] = useState([]);
  const [selectedTopic, setSelectedTopic] = useState(null);

  // Sample blog topics - could be generated by the agent in the future
  const sampleTopics = [
    "Artificial Intelligence in Healthcare",
    "Sustainable Living Practices",
    "Remote Work Best Practices",
    "Personal Finance Management",
    "Digital Privacy in 2023"
  ];

  const handleInputChange = (e) => {
    setUserInput(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (userInput.trim()) {
      onSendMessage(userInput);
      setUserInput('');
    }
  };

  const handleTopicSelect = (topic) => {
    setSelectedTopic(topic);
    onSendMessage(`I'd like to create a blog about: ${topic}`);
  };

  const handleGenerateTopics = () => {
    // In a real implementation, this would call the agent to generate topics
    // For now, we'll just use the sample topics
    setTopicIdeas(sampleTopics);
  };

  return (
    <div className="h-full flex flex-col">
      <div className="p-4 mb-4 bg-blue-100 rounded-lg shadow-sm">
        <h2 className="text-lg font-semibold flex items-center text-blue-800">
          <PenLine className="mr-2 h-5 w-5" />
          Blog Creation Assistant
        </h2>
        <p className="text-sm text-blue-700">
          I can help you create professional blog content. Share your topic or ask for suggestions to get started.
        </p>
      </div>

      {messages.length === 0 ? (
        <div className="p-6 flex-grow flex flex-col items-center justify-center">
          <h2 className="text-xl font-bold mb-6">Welcome to the Blog Creation Assistant</h2>
          
          <div className="mb-8 text-center max-w-xl">
            <p className="mb-4 text-gray-700">
              I can help you create engaging blog content by:
            </p>
            <p className="mb-2 text-gray-600 text-sm">• Suggesting compelling topics and headlines</p>
            <p className="mb-2 text-gray-600 text-sm">• Creating structured outlines for your blog posts</p>
            <p className="mb-2 text-gray-600 text-sm">• Generating full drafts with SEO-friendly content</p>
            <p className="mb-2 text-gray-600 text-sm">• Providing editing and improvement suggestions</p>
          </div>

          <div className="w-full border-t border-gray-200 mb-8"></div>
          
          <p className="text-gray-700 font-medium mb-4">Need inspiration? Try one of these topics:</p>
          
          {topicIdeas.length > 0 ? (
            <div className="flex flex-wrap justify-center gap-2 mb-6">
              {topicIdeas.map((topic, index) => (
                <button 
                  key={index} 
                  className="px-3 py-2 border border-blue-500 text-blue-500 rounded-md hover:bg-blue-50"
                  onClick={() => handleTopicSelect(topic)}
                >
                  {topic}
                </button>
              ))}
            </div>
          ) : (
            <button 
              className="mb-6 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
              onClick={handleGenerateTopics}
            >
              Show Topic Ideas
            </button>
          )}
          
          <p className="text-gray-700 font-medium mt-4">
            Or type your own blog topic below to get started
          </p>
        </div>
      ) : (
        <div className="flex-grow overflow-auto mb-4">
          <MessageList messages={messages} />
        </div>
      )}

      <form onSubmit={handleSubmit} className="mt-auto">
        <textarea
          className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none"
          rows={3}
          placeholder={messages.length === 0 
            ? "Enter a blog topic or request (e.g., 'Write a blog about sustainable living')" 
            : "Type your message here..."}
          value={userInput}
          onChange={handleInputChange}
          disabled={isLoading}
        />
        <button 
          className="w-full mt-2 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:bg-blue-300 disabled:cursor-not-allowed"
          type="submit" 
          disabled={!userInput.trim() || isLoading}
        >
          {isLoading ? (
            <div className="flex justify-center items-center">
              <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
            </div>
          ) : 'Send'}
        </button>
      </form>
    </div>
  );
};

export default BlogCreationView; 